using Project.Model;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Project.Views
{
    /// <summary>
    /// Interaction logic for RoutesReview.xaml
    /// </summary>
    public partial class RoutesReview : UserControl
    {

        ObservableCollection<Route> Routes = new ObservableCollection<Route>();

        public RoutesReview()
        {
            InitializeComponent();
        }

        public void TableRoutesLoad(object sender, RoutedEventArgs e)
        {
            fillRoutesTable();
        }

        public void fillRoutesTable()
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            Routes = new ObservableCollection<Route>(window.systemEntities.systemRoutes);
            tableRoutes.ItemsSource = Routes;
        }

        private void tableRoutes_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column.Header.ToString() == "StartingStation")
            {
                e.Column.Header = "Početna stanica ";
            }
            if (e.Column.Header.ToString() == "EndingStation")
            {
                e.Column.Header = "Krajnja stanica ";
            }
            if (e.Column.Header.ToString() == "Stations")
            {
                e.Column.Visibility = Visibility.Hidden;
            }
        }

        public void ShowAllRoutes(object sender, RoutedEventArgs e)
        {
            fillRoutesTable();
        }

        private void tableRoutes_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Detaljnije")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        public void ShowDetailsForRoute(object sender, RoutedEventArgs e)
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            Route selectedRoute = ((FrameworkElement)sender).DataContext as Route;
            startingStation.Text = selectedRoute.StartingStation.ToString();
            endingStation.Text = selectedRoute.EndingStation.ToString();
            stations.Text = selectedRoute.StartingStation.ToString();
            foreach (TrainStation station in selectedRoute.Stations)
            {
                stations.Text += " - " + station.ToString();
            }
            stations.Text += " - " + selectedRoute.EndingStation.ToString();
        }
    }
}
