using Project.Modals;
using Project.Model;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Project.Views
{
    /// <summary>
    /// Interaction logic for RoutesReview.xaml
    /// </summary>
    public partial class RoutesReview : UserControl
    {

        ObservableCollection<Route> Routes = new ObservableCollection<Route>();

        ObservableCollection<TrainStation> Stations = new ObservableCollection<TrainStation>();

        Route selectedRoute = null;

        double previousX;
        double previousY;

        public RoutesReview()
        {
            InitializeComponent();
        }

        public void TableRoutesLoad(object sender, RoutedEventArgs e)
        {
            fillRoutesTable();
        }

        public void fillRoutesTable()
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            Routes = new ObservableCollection<Route>(window.systemEntities.systemRoutes);
            tableRoutes.ItemsSource = Routes;
            Stations = new ObservableCollection<TrainStation>(window.systemEntities.systemTrainStations);
            startingStation.ItemsSource = Stations;
            endingStation.ItemsSource = Stations;
        }

        private void tableRoutes_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column.Header.ToString() == "StartingStation")
            {
                e.Column.Header = "Početna stanica ";
            }
            if (e.Column.Header.ToString() == "EndingStation")
            {
                e.Column.Header = "Krajnja stanica ";
            }
            if (e.Column.Header.ToString() == "Stations")
            {
                e.Column.Visibility = Visibility.Hidden;
            }
            if (e.Column.Header.ToString() == "Id")
            {
                e.Column.Visibility = Visibility.Hidden;
            }
        }

        public void ShowAllRoutes(object sender, RoutedEventArgs e)
        {
            fillRoutesTable();
        }

        private void tableRoutes_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Mrežni prikaz")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        private void Window_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            List<Point> newCoords = new List<Point>();
            MainWindow window = (MainWindow)Window.GetWindow(this);
            if (drawSurface.Visibility == Visibility.Visible && window.routesReviewPage.drawSurface.Visibility == Visibility.Visible)
            {
                for(int i = 0; i < drawSurface.Children.Count; i++)
                {
                    if (i % 2 == 1 || i == 0)
                    {
                        Border border = (Border)drawSurface.Children[i];
                        border.Height = drawSurface.ActualHeight / 10;
                        border.Width = routesGrid.ActualWidth / 7;
                        Label label = border.Child as Label;
                        label.FontSize = drawSurface.ActualHeight / 40;
                        Canvas.SetTop(border, (routesGrid.ActualHeight * Canvas.GetTop(border)) / e.PreviousSize.Height);
                        Canvas.SetLeft(border, (routesGrid.ActualWidth * Canvas.GetLeft(border)) / e.PreviousSize.Width);
                        Point point = new Point();
                        point.X = (routesGrid.ActualWidth * Canvas.GetLeft(border)) / e.PreviousSize.Width;
                        point.Y = (routesGrid.ActualHeight * Canvas.GetTop(border)) / e.PreviousSize.Height;

                        newCoords.Add(point);
                    }
                }

                int starting_sub_num = 2;
                for (int i = 0; i < drawSurface.Children.Count; i++)
                {
                    if (i % 2 == 0 && i > 0)
                    {
                        Line line = (Line)drawSurface.Children[i];
                        line.X1 = newCoords[i - starting_sub_num].X;
                        line.Y1 = newCoords[i - starting_sub_num].Y;

                        line.X2 = newCoords[i - starting_sub_num + 1].X;
                        line.Y2 = newCoords[i - starting_sub_num + 1].Y;

                        starting_sub_num++;
                    }
                    
                }
            }
        }

        public void ShowDetailsForRoute(object sender, RoutedEventArgs e)
        {
            selectedRoute = ((FrameworkElement)sender).DataContext as Route;
            MainWindow window = (MainWindow)Window.GetWindow(this);
            if (window.systemEntities.systemTrainStations[0].X == -1)
            {
                setStationsCoordinates();
            }
            ShowWebRoutes();
        }

        private void ShowWebRoutes()
        {
            transformWebView();
            double gridHeight = drawSurface.ActualHeight;
            double gridWidth = routesGrid.ActualWidth;
            int number = 1;
            CreateRectangle(selectedRoute.StartingStation, 0, gridHeight, gridWidth);
            foreach (TrainStation trainStation in selectedRoute.Stations)
            {
                CreateRectangle(trainStation, number, gridHeight, gridWidth);
                number += 2;
            }
            CreateRectangle(selectedRoute.EndingStation, number, gridHeight, gridWidth);
        }

        private void transformWebView()
        {
            routesGrid.Background.Opacity = 100;
            labelTitle.Visibility = Visibility.Hidden;
            labelFrom.Visibility = Visibility.Hidden;
            startingStation.Visibility = Visibility.Hidden;
            labelTo.Visibility = Visibility.Hidden;
            endingStation.Visibility = Visibility.Hidden;
            search.Visibility = Visibility.Hidden;
            reset.Visibility = Visibility.Hidden;
            tableRoutes.Visibility = Visibility.Hidden;
            drawSurface.Visibility = Visibility.Visible;
            back.Visibility = Visibility.Visible;
        }

        private void CreateRectangle(TrainStation trainStation, int number, double gridHeight, double gridWidth)
        {
            Border border = new Border();
            border.Height = gridHeight/10;
            border.Width = gridWidth/7;
            Label label = new Label();
            border.Background = new SolidColorBrush(System.Windows.Media.Colors.LightBlue);
            if (number == 0)
            {
                BrushConverter bc = new BrushConverter();
                border.BorderBrush = (Brush)bc.ConvertFrom("#191c4f");
                border.BorderThickness = new Thickness(5, 5, 5, 5);
                label.Content = "Početak: " + trainStation.Name;
            }
            else
            {
                border.BorderBrush = new SolidColorBrush(System.Windows.Media.Colors.Black);
                border.BorderThickness = new Thickness(3, 3, 3, 3);
                label.Content = trainStation.Name;
            }          
            label.FontFamily = new FontFamily("Arial black");
            label.FontSize = gridHeight/40;
            label.HorizontalAlignment = HorizontalAlignment.Center;
            label.VerticalAlignment = VerticalAlignment.Center;
            border.Child = label;

            drawSurface.Children.Insert(number, border);
            Canvas.SetTop(border, trainStation.Y);
            Canvas.SetLeft(border, trainStation.X);

            if (number != 0)
            {
                Line line = new Line();
                line.X1 = previousX;
                line.Y1 = previousY;
                line.X2 = trainStation.X;
                line.Y2 = trainStation.Y;
                line.StrokeThickness = 4;
                SolidColorBrush brush = new SolidColorBrush();
                brush.Color = Colors.Black;
                line.Stroke = brush;
                drawSurface.Children.Insert(number+1, line);
            }
            previousX = trainStation.X;
            previousY = trainStation.Y;

        }

        public void SearchRoutes(object sender, RoutedEventArgs e)
        {
            if (startingStation.SelectedItem != null || endingStation.SelectedItem != null)
            {
                ObservableCollection<Route> notMade = new ObservableCollection<Route>();
                if (startingStation.SelectedItem != null)
                    foreach (Route route in Routes)
                    {
                        if (!route.StartingStation.Equals(startingStation.SelectedItem) && !notMade.Contains(route)) notMade.Add(route);
                    }
                if (endingStation.SelectedItem != null)
                    foreach (Route route in Routes)
                    {
                        if (!route.EndingStation.Equals(endingStation.SelectedItem) && !route.Stations.Contains(endingStation.SelectedItem) && !notMade.Contains(route)) notMade.Add(route);
                    }
                foreach (Route route in notMade) Routes.Remove(route);
            }
            else
            {
                Error error = new Error("Niste uneli nijedan kriterijum za pretraživanje!");
                error.ShowDialog();
            }
        }

        public void ResetSearch(object sender, RoutedEventArgs e)
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            Routes = new ObservableCollection<Route>(window.systemEntities.systemRoutes);
            tableRoutes.ItemsSource = Routes;
            startingStation.SelectedItem = null;
            endingStation.SelectedItem = null;
        }

        public void BackOnSearch(object sender, RoutedEventArgs e)
        {
            transformFromWebView();
        }

        private void transformFromWebView()
        {
            routesGrid.Background.Opacity = 0;
            drawSurface.Visibility = Visibility.Hidden;
            labelTitle.Visibility = Visibility.Visible;
            labelFrom.Visibility = Visibility.Visible;
            startingStation.Visibility = Visibility.Visible;
            labelTo.Visibility = Visibility.Visible;
            endingStation.Visibility = Visibility.Visible;
            search.Visibility = Visibility.Visible;
            reset.Visibility = Visibility.Visible;
            tableRoutes.Visibility = Visibility.Visible;
            back.Visibility = Visibility.Hidden;
            drawSurface.Children.Clear();
            selectedRoute = null;
        }

        private void setStationsCoordinates()
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            double gridHeight = window.stationsPosition.drawSurface.ActualHeight;
            double gridWidth = window.stationsPosition.stationsGrid.ActualWidth;
            double diffHeight = gridHeight / (window.systemEntities.systemTrainStations.Count + 2);
            double diffWidth = gridWidth / (window.systemEntities.systemTrainStations.Count + 2);
            double posX = diffWidth;
            double posY = diffHeight;

            foreach (TrainStation trainstation in window.systemEntities.systemTrainStations)
            {
                trainstation.X = posX;
                trainstation.Y = posY;
                posX += diffWidth;
                posY += diffHeight;
            }
        }
    }
}
