using Project.Modals;
using Project.Model;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Project.Views
{
    /// <summary>
    /// Interaction logic for TrainCrud.xaml
    /// </summary>
    public partial class TrainCrud : UserControl
    {   
        ObservableCollection<Train> trains = new ObservableCollection<Train>();

        private ObservableCollection<Timetable> currentTimetables = new ObservableCollection<Timetable>();
        private Train currentTrain;

        public ObservableCollection<Timetable> CurrentTimetables
        {
            get { return currentTimetables; }
            set { currentTimetables = value; }
        }

        public bool isMainWindowOpened = true;

        public Train currentTrainCell;
        public TrainCrud()
        {
            InitializeComponent();
        }
        public void fillTrainTable()
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            trains = new ObservableCollection<Train>(window.systemEntities.systemTrains);
            tableTrains.ItemsSource = trains;
        }

        private void TrainCrudLoaded(object sender, RoutedEventArgs e)
        {
            fillTrainTable();
        }

        public void AddTrain(object sender, RoutedEventArgs e)
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            int maxIndex = window.systemEntities.systemTrains.Max(t => t.Number);
            window.systemEntities.systemTrains.Add(new Train(maxIndex + 1, "BrzaPtica"));
            fillTrainTable();
            Success success = new Success("Uspešno dodat voz broj " + (maxIndex + 1).ToString() + " prevoznika BrzaPtica.");
            success.ShowDialog();
        }

        private void tableTrains_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column.Header.ToString() == "Operator")
            {
                e.Column.Header = "Prevoznik";
            }
            if (e.Column.Header.ToString() == "Number")
            {
                e.Column.Header = "Broj voza";
                e.Column.IsReadOnly = true;
            }
        }

        public void DeleteTrain(object sender, RoutedEventArgs e)
        {
            YesNoModal yesNoModal = new YesNoModal("Da li ste sigurni da želite da obrišete odabrani voz?");
            yesNoModal.ShowDialog();
            if(yesNoModal.response)
            {
                MainWindow window = (MainWindow)Window.GetWindow(this);
                Train train = ((FrameworkElement)sender).DataContext as Train;
                List<Timetable> timetablesForRemoving = new List<Timetable>();
                foreach (Train t in window.systemEntities.systemTrains)
                {
                    if (t.Number == train.Number && t.Operator == train.Operator)
                    {
                        foreach (Timetable timetable in window.systemEntities.systemTimetables)
                        {
                            if (timetable.train.Number == train.Number)
                            {
                                timetablesForRemoving.Add(timetable);
                            }
                        }
                        foreach (Timetable timet in timetablesForRemoving)
                        {
                            window.systemEntities.systemTimetables.Remove(timet);
                        }
                        window.systemEntities.systemTrains.Remove(t);
                        fillTrainTable();
                        break;
                    }
                }
            }
        }

        private void tableTrains_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Obriši")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Redovi vožnje")
                {
                    item.DisplayIndex = grid.Columns.Count - 2;
                    break;
                }
            }
        }

        public void ShowAllTrains(object sender, RoutedEventArgs e)
        {
            fillTrainTable();
        }

        public void SearchTrains(object sender, RoutedEventArgs e)
        {
            if (searchText.Text.Length == 0)
            {
                Error error = new Error("Niste uneli nijedan karakter za pretraživanje!");
                error.ShowDialog();
            }
            else
            {
                MainWindow window = (MainWindow)Window.GetWindow(this);
                List<Train> searchedTrains = new List<Train>();
                foreach (Train train in window.systemEntities.systemTrains)
                {
                    if (train.Number.ToString().Contains(searchText.Text) || train.Operator.ToLower().Contains(searchText.Text.ToLower())){
                        searchedTrains.Add(train);
                    }
                }
                trains = new ObservableCollection<Train>(searchedTrains);
                tableTrains.ItemsSource = trains;
            }
            
        }

        public void ShowTimetables(object sender, RoutedEventArgs e)
        {
            isMainWindowOpened = false;

            tableTrains.Visibility = Visibility.Hidden;
            nameTrain.Visibility = Visibility.Hidden;
            addTrain.Visibility = Visibility.Hidden;
            searchText.Visibility = Visibility.Hidden;
            searchTrains.Visibility = Visibility.Hidden;
            showAllTrains.Visibility = Visibility.Hidden;

            MainWindow window = (MainWindow)Window.GetWindow(this);
            Train train = ((FrameworkElement)sender).DataContext as Train;
            currentTrain = train;
            List<Timetable> foundTimetables = new List<Timetable>();
            foreach (Timetable timetable in window.systemEntities.systemTimetables)
            {
                if (timetable.train.Equals(train))
                {
                    foundTimetables.Add(timetable);
                }
            }
            currentTimetables = new ObservableCollection<Timetable>(foundTimetables);
            tableTimetables.ItemsSource = currentTimetables;

            tableTimetables.Visibility = Visibility.Visible;
            nameTimetable.Visibility = Visibility.Visible;
            addTimetable.Visibility = Visibility.Visible;
            searchTextTimetable.Visibility = Visibility.Visible;
            searchTimetables.Visibility = Visibility.Visible;
            showAllTimetables.Visibility = Visibility.Visible;
            back.Visibility = Visibility.Visible;
        }

        private void tableTimetables_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Obriši")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        private void tableTimetables_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column.Header.ToString() == "startTime")
            {
                e.Column.Header = "Polazak ";
                e.Column.IsReadOnly = true;
            }
            if (e.Column.Header.ToString() == "startDate")
            {
                e.Column.Header = "Datum polaska ";
                e.Column.IsReadOnly = true;
            }
            if (e.Column.Header.ToString() == "endTime")
            {
                e.Column.Header = "Dolazak ";
                e.Column.IsReadOnly = true;
            }
            if (e.Column.Header.ToString() == "endDate")
            {
                e.Column.Header = "Datum dolaska ";
                e.Column.IsReadOnly = true;
            }
            if (e.Column.Header.ToString() == "id")
            {
                e.Column.Header = "Broj reda vožnje ";
                e.Column.IsReadOnly = true;
            }
            if (e.Column.Header.ToString() == "Route")
            {
                e.Column.Visibility = Visibility.Hidden;
            }
            if (e.Column.Header.ToString() == "train")
            {
                e.Column.Visibility = Visibility.Hidden;
            }
            if (e.Column is DataGridTextColumn textColumn)
                textColumn.Binding = new Binding(e.PropertyName) { UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged };
        }

        public void DeleteTimetable(object sender, RoutedEventArgs e)
        {
            YesNoModal yesNoModal = new YesNoModal("Da li ste sigurni da želite da obrišete odabrani red vožnje za odabrani voz?");
            yesNoModal.ShowDialog();
            if (yesNoModal.response)
            {
                MainWindow window = (MainWindow)Window.GetWindow(this);
                Timetable timetable = ((FrameworkElement)sender).DataContext as Timetable;
                currentTimetables.Remove(timetable);
                foreach (Timetable t in window.systemEntities.systemTimetables)
                {
                    if (t.id == timetable.id && currentTrain.Number == timetable.train.Number)
                    {
                        window.systemEntities.systemTimetables.Remove(t);
                        break;
                    }
                }
            }
        }

        public void AddTimetable(object sender, RoutedEventArgs e)
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            int maxIndex = window.systemEntities.systemTimetables.Max(t => t.id);
            DateTime nextDay = DateTime.
                ParseExact(window.systemEntities.systemTimetables[maxIndex - 1].endDate, "dd.MM.yyyy.", System.Globalization.CultureInfo.GetCultureInfo("es-ES").DateTimeFormat).AddDays(1);
            string nextDayString = nextDay.ToString("dd.MM.yyyy.");
            window.systemEntities.systemTimetables.Add(new Timetable(maxIndex + 1, "10:00", nextDayString, "12:00", nextDayString, currentTrain, window.systemEntities.systemRoutes[0]));
            currentTimetables.Add(new Timetable(maxIndex + 1, "10:00", nextDayString, "12:00", nextDayString, currentTrain, window.systemEntities.systemRoutes[0]));
            Success success = new Success("Uspešno dodat novi red vožnje!");
            success.ShowDialog();
        }

        public void SearchTimetables(object sender, RoutedEventArgs e)
        {
            if (searchTextTimetable.Text.Length == 0)
            {
                Error error = new Error("Niste uneli nijedan karakter za pretraživanje!");
                error.ShowDialog();
            }
            else
            {
                List<Timetable> searchedTimetables = new List<Timetable>();
                foreach (Timetable timetable in CurrentTimetables)
                {
                    if (timetable.startDate.Contains(searchTextTimetable.Text) || timetable.startTime.Contains(searchTextTimetable.Text) ||
                        timetable.endDate.Contains(searchTextTimetable.Text) || timetable.endTime.Contains(searchTextTimetable.Text) ||
                            timetable.Route.Id.ToString().Contains(searchTextTimetable.Text))
                    {
                        searchedTimetables.Add(timetable);
                    }
                }
                currentTimetables = new ObservableCollection<Timetable>(searchedTimetables);
                tableTimetables.ItemsSource = currentTimetables;
            }
        }

        public void ShowAllTimetables(object sender, RoutedEventArgs e)
        {
            MainWindow window = (MainWindow)Window.GetWindow(this);
            List<Timetable> foundTimetables = new List<Timetable>();
            foreach (Timetable timetable in window.systemEntities.systemTimetables)
            {
                if (timetable.train.Equals(currentTrain))
                {
                    foundTimetables.Add(timetable);
                }
            }
            currentTimetables = new ObservableCollection<Timetable>(foundTimetables);
            tableTimetables.ItemsSource = currentTimetables;
        }

        public void Back(object sender, RoutedEventArgs e)
        {
            isMainWindowOpened = true;

            tableTrains.Visibility = Visibility.Visible;
            nameTrain.Visibility = Visibility.Visible;
            addTrain.Visibility = Visibility.Visible;
            searchText.Visibility = Visibility.Visible;
            searchTrains.Visibility = Visibility.Visible;
            showAllTrains.Visibility = Visibility.Visible;

            tableTimetables.Visibility = Visibility.Hidden;
            nameTimetable.Visibility = Visibility.Hidden;
            addTimetable.Visibility = Visibility.Hidden;
            searchTextTimetable.Visibility = Visibility.Hidden;
            searchTimetables.Visibility = Visibility.Hidden;
            showAllTimetables.Visibility = Visibility.Hidden;
            back.Visibility = Visibility.Hidden;
        }

        private void tableTrains_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            string columnName = e.Column.Header.ToString();
            if (columnName == "Prevoznik")
            {
                int index = e.Row.GetIndex();
                var element = e.EditingElement as TextBox;
                string s = (((TextBox)e.EditingElement).Text);
                if (s.Length != 0)
                {
                    MainWindow window = (MainWindow)Window.GetWindow(this);
                    window.systemEntities.systemTrains[index].Operator = s;
                    Success success = new Success("Uspešno izmenjen prevoznik!");
                    success.Show();
                }
                else
                {
                    element.Text = currentTrainCell.Operator;
                    Error error = new Error("Nije unet nijedan karakter!");
                    error.ShowDialog();
                }
            }
            ButtonAutomationPeer peer = new ButtonAutomationPeer(showAllTrains);
            IInvokeProvider invokeProv = peer.GetPattern(PatternInterface.Invoke) as IInvokeProvider;
            invokeProv.Invoke();
        }

        private void tableTrains_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            if (e.Column.Header.ToString() == "Prevoznik")
            {
                TextBlock tb = (TextBlock)e.Column.GetCellContent(e.Row);
                Train item = (Train)tb.DataContext;
                currentTrainCell = item;
            }
        }

        public void IsMainWindowOpened(object sender, CanExecuteRoutedEventArgs e)
        {
            if (isMainWindowOpened)
            {
                e.CanExecute = true;
            }
            else
            {
                e.CanExecute = false;
            }
        }

        public void IsMainWindowNotOpened(object sender, CanExecuteRoutedEventArgs e)
        {
            if (isMainWindowOpened)
            {
                e.CanExecute = false;
            }
            else
            {
                e.CanExecute = true;
            }
        }
    }
}